# src/main.py
"""
Main entry point for the invoice automation CLI application.

This module defines the main Typer application and registers all available
commands. It serves as the primary interface for users interacting with
the invoice automation system.
"""

import sys
from pathlib import Path
from typing import Any

import typer
from rich.console import Console
from rich.traceback import install

from .commands.fetch import fetch_command
from .commands.status import status_command

# Install rich traceback handler for better error display
install(show_locals=True)

console = Console()

# Create the main Typer application
app = typer.Typer(
    name="invoice-automation",
    help="Automate invoice retrieval from Google Ads and Meta Ads",
    add_completion=False,
    rich_markup_mode="rich",
    context_settings={"help_option_names": ["-h", "--help"]},
)

# Register commands
app.command("fetch", help="Fetch invoices from configured providers")(fetch_command)
app.command("status", help="Check provider configuration and API connections")(status_command)


def version_callback(value: bool) -> None:
    """
    Display version information and exit.
    
    Args:
        value: Whether version was requested
    """
    if value:
        console.print("invoice-automation version 0.1.0")
        raise typer.Exit()


@app.callback()
def main(
    version: bool = typer.Option(
        False,
        "--version",
        "-V",
        callback=version_callback,
        is_eager=True,
        help="Show version and exit",
    ),
) -> None:
    """
    Invoice Automation CLI - Automate invoice retrieval from advertising platforms.
    
    This tool helps agencies and businesses automatically retrieve, download,
    and organize invoices from Google Ads and Meta Ads (Facebook) accounts.
    
    Features:
    • Retrieve invoices from Meta Ads and Google Ads APIs
    • Download invoice PDFs with automatic retry logic
    • Organize files using configurable folder structures
    • Handle multiple client accounts and providers
    • Comprehensive error handling and logging
    
    Getting Started:
    1. Copy .env.example to .env and configure your API credentials
    2. Run 'invoice-automation status' to test your configuration
    3. Run 'invoice-automation fetch' to retrieve invoices
    
    For detailed documentation and examples, visit:
    https://github.com/your-repo/invoice-automation
    """
    pass


@app.command()
def setup(
    provider: str = typer.Option(
        "both",
        "--provider",
        "-p",
        help="Provider to set up: meta, google, or both",
    ),
    interactive: bool = typer.Option(
        True,
        "--interactive/--non-interactive",
        help="Use interactive setup wizard",
    ),
) -> None:
    """
    Interactive setup wizard for configuring API credentials.
    
    This command guides you through the process of setting up API credentials
    for Meta Ads and Google Ads, creating the necessary configuration files.
    
    Examples:
        invoice-automation setup --provider meta
        invoice-automation setup --interactive
    """
    if interactive:
        _run_interactive_setup(provider)
    else:
        _display_setup_instructions(provider)


def _run_interactive_setup(provider: str) -> None:
    """
    Run the interactive setup wizard.
    
    Args:
        provider: Provider to set up
    """
    console.print("[bold blue]Invoice Automation Setup Wizard[/bold blue]\n")
    
    env_path = Path(".env")
    
    if env_path.exists():
        overwrite = typer.confirm(
            f".env file already exists. Do you want to overwrite it?",
            default=False,
        )
        if not overwrite:
            console.print("[yellow]Setup cancelled.[/yellow]")
            return
    
    console.print("This wizard will help you configure your API credentials.\n")
    
    config_lines = [
        "# Invoice Automation Configuration",
        "# Generated by setup wizard",
        "",
        "# Application Configuration",
        "OUTPUT_DIR=./invoices",
        "LOG_LEVEL=INFO",
        "MAX_RETRIES=3",
        "RETRY_DELAY=1.0",
        "TIMEOUT_SECONDS=30",
        "DEBUG=false",
        "",
    ]
    
    if provider in ["meta", "both"]:
        console.print("[bold]Meta Ads Configuration[/bold]")
        console.print("You'll need a Meta Business Manager account with Finance role.")
        console.print("Visit https://business.facebook.com/ to get your credentials.\n")
        
        business_id = typer.prompt("Meta Business ID")
        access_token = typer.prompt("Meta Access Token", hide_input=True)
        api_version = typer.prompt("Meta API Version", default="v21.0")
        
        config_lines.extend([
            "# Meta Ads Configuration",
            f"META_BUSINESS_ID={business_id}",
            f"META_ACCESS_TOKEN={access_token}",
            f"META_API_VERSION={api_version}",
            "",
        ])
    
    if provider in ["google", "both"]:
        console.print("[bold]Google Ads Configuration[/bold]")
        console.print("You'll need Google Ads API credentials and OAuth2 setup.")
        console.print("Visit https://developers.google.com/google-ads/api/ for setup instructions.\n")
        
        customer_id = typer.prompt("Google Ads Customer ID")
        client_id = typer.prompt("OAuth2 Client ID")
        client_secret = typer.prompt("OAuth2 Client Secret", hide_input=True)
        refresh_token = typer.prompt("OAuth2 Refresh Token", hide_input=True)
        developer_token = typer.prompt("Google Ads Developer Token", hide_input=True)
        
        config_lines.extend([
            "# Google Ads Configuration",
            f"GOOGLE_CUSTOMER_ID={customer_id}",
            f"GOOGLE_CLIENT_ID={client_id}",
            f"GOOGLE_CLIENT_SECRET={client_secret}",
            f"GOOGLE_REFRESH_TOKEN={refresh_token}",
            f"GOOGLE_DEVELOPER_TOKEN={developer_token}",
            "",
        ])
    
    # Write configuration file
    try:
        with open(env_path, "w") as f:
            f.write("\n".join(config_lines))
        
        console.print(f"\n[green]Configuration saved to {env_path}[/green]")
        console.print("\nNext steps:")
        console.print("1. Run 'invoice-automation status' to test your configuration")
        console.print("2. Run 'invoice-automation fetch' to retrieve invoices")
        
    except Exception as e:
        console.print(f"[red]Failed to save configuration: {e}[/red]")
        raise typer.Exit(1)


def _display_setup_instructions(provider: str) -> None:
    """
    Display manual setup instructions.
    
    Args:
        provider: Provider to show instructions for
    """
    console.print("[bold blue]Manual Setup Instructions[/bold blue]\n")
    
    console.print("1. Copy .env.example to .env:")
    console.print("   [cyan]cp .env.example .env[/cyan]\n")
    
    console.print("2. Edit .env with your preferred editor and fill in the credentials:\n")
    
    if provider in ["meta", "both"]:
        console.print("[bold]Meta Ads Credentials:[/bold]")
        console.print("• META_BUSINESS_ID: Your Meta Business Manager ID")
        console.print("• META_ACCESS_TOKEN: Graph API access token with Finance role")
        console.print("• META_API_VERSION: API version (default: v21.0)")
        console.print("• Get these from: https://business.facebook.com/\n")
    
    if provider in ["google", "both"]:
        console.print("[bold]Google Ads Credentials:[/bold]")
        console.print("• GOOGLE_CUSTOMER_ID: Your Google Ads customer ID")
        console.print("• GOOGLE_CLIENT_ID: OAuth2 client ID")
        console.print("• GOOGLE_CLIENT_SECRET: OAuth2 client secret")
        console.print("• GOOGLE_REFRESH_TOKEN: OAuth2 refresh token")
        console.print("• GOOGLE_DEVELOPER_TOKEN: Google Ads developer token")
        console.print("• Setup guide: https://developers.google.com/google-ads/api/\n")
    
    console.print("3. Test your configuration:")
    console.print("   [cyan]invoice-automation status[/cyan]\n")
    
    console.print("4. Fetch invoices:")
    console.print("   [cyan]invoice-automation fetch[/cyan]")


def handle_exception(exc_type: Any, exc_value: Any, exc_traceback: Any) -> None:
    """
    Global exception handler for unhandled exceptions.
    
    Args:
        exc_type: Exception type
        exc_value: Exception instance
        exc_traceback: Traceback object
    """
    if issubclass(exc_type, KeyboardInterrupt):
        # Handle Ctrl+C gracefully
        console.print("\n[yellow]Operation cancelled by user[/yellow]")
        sys.exit(1)
    else:
        # Use rich to display the exception
        console.print_exception(show_locals=True)


# Install global exception handler
sys.excepthook = handle_exception


if __name__ == "__main__":
    app()
